### ISSUE TITLE
DownloadThroughUITests fails at "no Download control" — undiagnosed

### ISSUE THREAD

**Issue by chipi** [chipi/podcast_scraper#2120]
`make test-app-ios-sim-download` fails. The suite reaches the episode page and
then never finds the download control:

```
DownloadThroughUITests.swift:142: error: failed - no Download control on
  Signal, Noise, and the Space Between — signed out, or the episode never loaded
DownloadThroughUITests.swift:142: error: failed - no Download control on
  The Conversation About Conversations — signed out, or the episode never loaded
```

## Context: this suite only recently became runnable

It was failing earlier for two DIFFERENT reasons, both fixed in #2118:

1. `Journey.scrollTo` gave up after a fixed 8 swipes. Moving Downloaded to the end
   of Saved and adding a stats block above Profile's "Sign out" pushed both anchors
   past that budget → "the UI download did not land" when it had landed fine.
2. A failed scroll left the app at the bottom of the page, so the masthead ended up
   at y = -623 and the next step reported "neither Sign in nor Sign out present" on
   a healthy signed-in app.

With those fixed the suite gets past sign-in and download, and fails here instead.
So this is the *third* failure in a chain, not a regression from the first two.

## What I checked, and ruled out

- **Services are up.** api :8011 → 200, origin :4174 → 200, media host answering.
- **The labels are unchanged.** `downloads.download = 'Download for offline'` and
  `downloads.downloaded = 'Downloaded — tap to remove'` — exactly what the spec
  queries.
- **#2118 does not touch the episode page.** `git diff` over that branch shows no
  change to `EpisodeActions.vue`; only `DownloadedList.vue` (+18/-1).

So I have no evidence it is caused by #2118, and equally none that it is not. It
is genuinely undiagnosed — I stopped here deliberately rather than guess.

## Where to look next

The spec scopes the query to the episode page (`app.otherElements["main"]`), which
was deliberate — an unscoped `firstMatch` once matched a different episode that was
already downloaded and reported a success it had not produced. Worth checking
whether `main` is the right container after the player/episode surface changes, and
whether the control is simply below the fold inside it (the same class of bug as the
two already fixed — `Journey.scrollTo` is the tool for that now).

The failure message conflates two causes ("signed out, OR the episode never
loaded"). Splitting it would say which.

## Repro

```
make test-app-ios-native-full          # chains build, install, origin, sign-in
# or just this suite, with services already up:
cd web/learning-player/ios/uitests && xcodebuild test \
  -project OfflineSpike.xcodeproj -scheme OfflineSpikeUITests \
  -destination 'platform=iOS Simulator,name=iPhone 17' \
  -only-testing:OfflineSpikeUITests/DownloadThroughUITests \
  -derivedDataPath /tmp/lp-ios-dd-uitests CODE_SIGNING_ALLOWED=NO
```

Note the make recipe pipes xcodebuild through `tail -20`, which truncates the
`=====TREE=====` dumps the spec prints on failure. Run it directly to see them.

Local only — macOS + simulator. CI is Linux and does not run this.

**Comment by chipi** [comment]
## Ruled out: this is NOT the state-leak of #2091

#2091 (per-suite accounts + `startClean` forcing offline OFF) is now implemented, and the suite
still fails — with the **same message, same episode, same assertion** as it did before any test-tier
change today:

```
before:  ...is not in the Downloaded list — the UI download did not land                    (line 69)
after:   ...is not in the Downloaded list after scrolling to the end of Saved — ...          (line 79)
```

Only the wording and line number moved (I added the scroll and reworded it). So the leaked-state
hypothesis I raised when filing this is **wrong** — isolation does not fix it.

## What #2091 DID fix here

An intermediate run failed earlier at `"no Download control on <episode> — signed out, or the
episode never loaded"`. That one WAS state: forced-offline left on by another suite meant the
episode page could not load, so the control was genuinely absent. `startClean` removes it, and the
suite now gets past download and all the way to the Library assertion.

## Where it actually fails

The downloads themselves report success — the helper waits for `"Downloaded — tap to remove"` on the
episode page and that passes, twice. The failure is the *Library* not listing them.

Worth investigating: the download registry is namespaced **per account**
(`downloads.registry.<namespace>`, `stores/downloads.ts:106-120`) — files survive sign-out but the
LIST does not. Whether the namespace in play when the download is written matches the one the
Downloaded section reads is unverified, and is the first thing I would check.

Not chasing further per operator scoping; recording the evidence so the next attempt does not
re-test the isolation hypothesis.

**Comment by chipi** [comment]
## Evidence from the simulator: nothing was persisted at all

Inspected the app's live container straight after a failing run (the Preferences plist was written
at 20:29:45, during the run that ended 20:31:24, so this is the current install — not a stale one).

**Preferences holds four keys, and none is a downloads registry:**

```
CapacitorStorage.auth.me
CapacitorStorage.lp_native_token
CapacitorStorage.playback.positions.u_1e9f7e3c36157a4b6262cafc
CapacitorStorage.playback.positions.u_bc76c56b88bcec16904531b0
```

No `downloads.registry.*` key of any namespace. **Zero `.mp3`/`.m4a` files anywhere in the
container** — only `Library/NoCloud/content-cache/`.

Meanwhile the episode page reported success: the spec's `download()` helper waits for
`"Downloaded — tap to remove"` and that appeared, twice. So **the app said the download completed
while nothing reached disk or the registry.**

## Why this is sharper than it looks

`mark()` writes a `queued` entry and persists it BEFORE any transfer starts. So a registry key
should exist even if the transfer itself failed. It does not. That points upstream of the transfer —
either `mark()` is not reached, or it returns early (it no-ops when the state is already
`downloaded`/`downloading`/`queued`).

## Ruled out

- **The media host.** `/audio/<fixture>.mp3` returns 200 with 703678 bytes, both directly on :18765
  and proxied through the origin on :4174.
- **Cross-suite state leakage.** #2091 is implemented (per-suite accounts + `startClean`) and the
  failure is byte-identical to the pre-#2091 one. It DID fix a different, intermediate failure —
  `"no Download control"` — which was forced-offline left on by another suite.
- **A permanently-unloadable store.** I hypothesised that `load()`'s early return leaves
  `this.loaded` false forever, making every `_persist()` a silent no-op while `_put` fills memory —
  which would match the symptom exactly. **Tested it: the hypothesis is wrong.** `ensureLoaded()`
  re-enters `load()` whenever `loaded` is false, so the store self-heals. The test is committed as a
  regression guard even though it passes.

## Next step

Needs the WKWebView console, which the XCUITest harness does not capture. The question is narrow:
does `mark()` run, and what does it return? A `console.log` at that call site, or surfacing the
store's `errorKind` in the UI where a test can read it, would settle it.
